### ISSUE TITLE
Package name discrepancy

### ISSUE THREAD

**Issue by geoah** [1995parham/linkedlist.go#4]
Hey there, first of all thank you for sharing this lib! :)

There seems to be an discrepancy between the git repository name (linkedlist.go) and the package name defined in go.mod (linkedlist), and go mod really doesn't like it. Using a replace works fine, but is not ideal as they don't get inherited from other packages pulling the package with the replace. -- Would it be possible to update either?

Thank you very much in advance.

**Comment by 1995parham** [comment]
Yeah, you are right. I forgot to fix this and I will do it. thanks for mentioning this.
